-- Glossary Terms seed data
DELETE FROM "GlossaryTerm";

INSERT INTO "GlossaryTerm" (id, slug, term, definition, long_definition, category, related_slugs, status, created_at, updated_at) VALUES
('gloss-001', 'avm-automated-valuation-model', 'AVM (Automated Valuation Model)', 'An AI-powered system that estimates property values by analyzing data from public records, recent sales, and market trends.', 'AVMs use machine learning to estimate property values by analyzing thousands of data points including comparable sales, property characteristics, and market trends. Major AVMs include Zillow Zestimate (100M+ homes, 2.4% median error) and Quantarium (150M+ properties with satellite imagery). AVMs are widely used for listing price guidance, preliminary underwriting, and portfolio monitoring.', 'Property Valuation', '["predictive-analytics","machine-learning","cma"]', 'PUBLISHED', NOW(), NOW());

INSERT INTO "GlossaryTerm" (id, slug, term, definition, long_definition, category, related_slugs, status, created_at, updated_at) VALUES
('gloss-002', 'predictive-analytics', 'Predictive Analytics', 'The use of AI and statistical algorithms to identify future outcomes based on historical data.', 'Predictive analytics combines historical transaction data, property characteristics, demographic shifts, and consumer behavior to forecast future outcomes. Common applications include identifying likely sellers, forecasting price appreciation, and scoring leads by conversion probability. Platforms like Revaluate analyze 2,000+ data points per household, achieving 70-80% move prediction accuracy.', 'Data Science', '["machine-learning","lead-scoring","avm"]', 'PUBLISHED', NOW(), NOW());

INSERT INTO "GlossaryTerm" (id, slug, term, definition, long_definition, category, related_slugs, status, created_at, updated_at) VALUES
('gloss-003', 'nlp-natural-language-processing', 'NLP (Natural Language Processing)', 'A branch of AI enabling computers to understand, interpret, and generate human language.', 'NLP powers natural language property search, automated listing description generation, AI chatbots for buyer inquiries, and sentiment analysis of lead communications. Platforms like Zillow, Styldod, and Mosaik integrate NLP to improve search and content generation.', 'AI Technology', '["machine-learning","deep-learning"]', 'PUBLISHED', NOW(), NOW());

INSERT INTO "GlossaryTerm" (id, slug, term, definition, long_definition, category, related_slugs, status, created_at, updated_at) VALUES
('gloss-004', 'computer-vision', 'Computer Vision', 'AI technology that analyzes and interprets visual information from images and videos.', 'Computer vision in real estate identifies room types, architectural features, and property conditions from photos. Platforms like Restb.ai recognize 100+ property features for automated MLS compliance checking, visual property search, and property condition assessment for appraisal support.', 'AI Technology', '["deep-learning","digital-twin","3d-rendering"]', 'PUBLISHED', NOW(), NOW());

INSERT INTO "GlossaryTerm" (id, slug, term, definition, long_definition, category, related_slugs, status, created_at, updated_at) VALUES
('gloss-005', 'digital-twin', 'Digital Twin', 'A virtual 3D replica of a physical property enabling remote walkthroughs and spatial analysis.', 'Digital twins are interactive, dimensionally accurate 3D models of properties. Matterport leads with 10M+ spaces captured. Cortex AI automatically identifies rooms, objects, and features within the 3D model. Digital twins enable immersive virtual tours, automated floor plans, and remote property inspection. Particularly valuable for luxury listings and out-of-town buyers.', 'Virtual Reality', '["3d-rendering","computer-vision"]', 'PUBLISHED', NOW(), NOW());

INSERT INTO "GlossaryTerm" (id, slug, term, definition, long_definition, category, related_slugs, status, created_at, updated_at) VALUES
('gloss-006', 'lead-scoring', 'Lead Scoring', 'AI-driven method of ranking sales leads by their likelihood to convert, based on behavioral data.', 'AI lead scoring analyzes email opens, property views, search history, SMS responses, and website visit duration to assign real-time conversion probability scores. Unlike static rules, AI scoring updates continuously as behavior changes. CINC reports 30-40% improvement in lead-to-appointment rates with real-time AI scoring.', 'CRM', '["predictive-analytics","automated-nurture-sequence"]', 'PUBLISHED', NOW(), NOW());

INSERT INTO "GlossaryTerm" (id, slug, term, definition, long_definition, category, related_slugs, status, created_at, updated_at) VALUES
('gloss-007', 'automated-nurture-sequence', 'Automated Nurture Sequence', 'AI-driven communications (email, SMS, calls) that automatically engage and qualify leads over time.', 'Automated nurture replaces manual follow-up with AI-orchestrated multi-channel communication flows. A sequence might include immediate SMS after inquiry, personalized emails with relevant listings, and scheduled check-in calls. CINC AI Personal Assistant conducts two-way SMS conversations and schedules appointments. Teams report 3-5x ROI through improved conversion of otherwise cold leads.', 'CRM', '["lead-scoring","predictive-analytics"]', 'PUBLISHED', NOW(), NOW());

INSERT INTO "GlossaryTerm" (id, slug, term, definition, long_definition, category, related_slugs, status, created_at, updated_at) VALUES
('gloss-008', 'roi-analysis', 'ROI Analysis', 'Calculation of return on investment — AI-enhanced to factor in market trends and appreciation forecasts.', 'AI-powered ROI tools like Plunk and HouseCanary evaluate renovation ROI, rental income projections, portfolio performance across multiple properties, and buy-vs-rent analysis incorporating tax implications and appreciation forecasts. These tools analyze far more variables than manual spreadsheet models, providing more nuanced investment guidance.', 'Analytics', '["predictive-analytics","avm"]', 'PUBLISHED', NOW(), NOW());

INSERT INTO "GlossaryTerm" (id, slug, term, definition, long_definition, category, related_slugs, status, created_at, updated_at) VALUES
('gloss-009', 'virtual-staging', 'Virtual Staging', 'The use of AI to digitally furnish and decorate empty rooms in property photos.', 'AI virtual staging uses computer vision and generative AI to analyze room dimensions and lighting, then digitally insert furniture and decor at the correct scale. Styldod offers staging from $16/image vs $1,500-$3,000/month for traditional staging. Listings with staged photos receive 40% more views. Multiple design styles can be applied to the same room.', 'Marketing', '["computer-vision","3d-rendering"]', 'PUBLISHED', NOW(), NOW());

INSERT INTO "GlossaryTerm" (id, slug, term, definition, long_definition, category, related_slugs, status, created_at, updated_at) VALUES
('gloss-010', 'geospatial-analytics', 'Geospatial Analytics', 'AI-powered analysis of location-based data combining satellite imagery, mapping, and property records.', 'Geospatial analytics integrates satellite imagery, GIS mapping, property records, and demographic databases to analyze real estate at scale. Applications include assessing neighborhood quality from aerial imagery, flood risk analysis, land-use pattern identification, and market heat maps. Quantarium uses geospatial analytics as a key differentiator for its enterprise AVM.', 'Data Science', '["predictive-analytics","computer-vision","avm"]', 'PUBLISHED', NOW(), NOW());

INSERT INTO "GlossaryTerm" (id, slug, term, definition, long_definition, category, related_slugs, status, created_at, updated_at) VALUES
('gloss-011', '3d-rendering', '3D Rendering', 'The process of creating photorealistic images from 3D models for property marketing.', '3D rendering converts spatial data into lifelike visual representations. It powers Matterport virtual tours, architectural visualization for new construction, virtual renovation previews, and commercial property fly-throughs. AI has dramatically reduced rendering time from hours to seconds per frame, making 3D visualization accessible for everyday residential listings.', 'Virtual Reality', '["digital-twin","virtual-staging"]', 'PUBLISHED', NOW(), NOW());

INSERT INTO "GlossaryTerm" (id, slug, term, definition, long_definition, category, related_slugs, status, created_at, updated_at) VALUES
('gloss-012', 'machine-learning', 'Machine Learning', 'Core AI technology where algorithms improve through experience by analyzing data patterns.', 'Machine learning is the foundational technology behind most real estate AI applications. It powers AVMs that estimate property values, predictive models that identify likely sellers, recommendation engines that match buyers to properties, and computer vision systems that analyze property photos. Its key advantage is identifying complex, non-linear relationships across thousands of variables.', 'AI Technology', '["deep-learning","predictive-analytics","nlp"]', 'PUBLISHED', NOW(), NOW());

INSERT INTO "GlossaryTerm" (id, slug, term, definition, long_definition, category, related_slugs, status, created_at, updated_at) VALUES
('gloss-013', 'deep-learning', 'Deep Learning', 'Advanced machine learning using multi-layered neural networks for complex AI applications.', 'Deep learning uses artificial neural networks with multiple layers to process complex data. In real estate, it powers computer vision that recognizes 100+ property features in photos, natural language models for listing descriptions and chatbots, and valuation models analyzing satellite imagery. It improves with more data, benefiting large-scale platforms like Zillow and Quantarium.', 'AI Technology', '["machine-learning","computer-vision","nlp"]', 'PUBLISHED', NOW(), NOW());

INSERT INTO "GlossaryTerm" (id, slug, term, definition, long_definition, category, related_slugs, status, created_at, updated_at) VALUES
('gloss-014', 'cma', 'Comparative Market Analysis (CMA)', 'A method of estimating property value by comparing to similar recently sold properties — increasingly AI-enhanced.', 'A CMA evaluates a property against recently sold comparable properties with similar characteristics. AI-enhanced CMAs instantly identify the most relevant comps, adjust for feature differences, weight by recency and proximity, and generate professional reports in minutes. Combines algorithmic analysis with agent expertise — the preferred method for listing presentations and buyer consultations.', 'Property Valuation', '["avm","predictive-analytics"]', 'PUBLISHED', NOW(), NOW());

INSERT INTO "GlossaryTerm" (id, slug, term, definition, long_definition, category, related_slugs, status, created_at, updated_at) VALUES
('gloss-015', 'proptech', 'PropTech', 'Property Technology — the broad category of software and tools that innovate in the real estate industry.', 'PropTech encompasses all technology applied to real estate: AI valuation, virtual tours, digital transactions, smart home tech, and property management software. The sector attracted $15B+ in venture capital in 2024. Subcategories include Residential PropTech, Commercial PropTech, ConTech (construction), and FinTech for real estate. AI is the fastest-growing segment within PropTech.', 'Industry', '["avm","machine-learning","digital-twin"]', 'PUBLISHED', NOW(), NOW());
